import type { ProjectConfig } from "../types.js";
import { writeFile } from "../utils.js";
import { join } from "node:path";

/**
 * Generates an llms.txt route in Next.js projects or a static llms.txt for other frameworks.
 * This gives LLMs context about the registry when they encounter the project.
 */
export function generateLlmsTxt(config: ProjectConfig): void {
  const dir = config.directory;
  const name = config.registryName;
  const isGithub = config.target === "github";
  const slug = config.githubSlug || `<owner>/${name}`;
  const namespace = config.useNamespace ? config.namespace : null;

  const installCmd = isGithub
    ? `npx shadcn@latest add ${slug}/<component>`
    : namespace
      ? `npx shadcn@latest add ${namespace}/<component>`
      : `npx shadcn@latest add ${config.homepage}/r/<component>.json`;

  const registryAddCmd =
    !isGithub && namespace
      ? `npx shadcn@latest registry add ${namespace}=${config.homepage}/r/{name}.json`
      : "";

  const content = `# ${name}

> A custom shadcn component registry.

## Overview

${name} is a component registry built on the [shadcn registry protocol](https://ui.shadcn.com/docs/registry). Components are distributed as source code that users install with the shadcn CLI.

## Installation

${registryAddCmd ? `Add the registry:\n\n${registryAddCmd}\n\nThen install components:\n\n${installCmd}` : `Install components:\n\n${installCmd}`}

## Registry URL

${isGithub ? `GitHub source registry: ${slug} (the shadcn CLI reads registry.json directly from GitHub — no build, no hosted JSON).` : `${config.homepage}/r/registry.json`}

## Project Structure

- registry.json — Registry definition (source of truth)
- registry/${config.style}/ui/ — Component source files
- components.json — shadcn configuration
${isGithub ? "" : `- public/r/ — Built registry JSON (generated by \`shadcn build\`)\n`}${config.docsEngine !== "none" ? "- content/docs/ — Documentation pages (MDX)\n" : ""}
## Adding Components

Use the CLI:

npx create-scn-stack add-component <name> -d "Description"
npx create-scn-stack add-hook <name> -d "Description"
npx create-scn-stack add-block <name> -d "Description"

Or manually create files in registry/${config.style}/ui/ and update registry.json.

## Build

${isGithub ? "This is a GitHub source registry — there is no build step. Commit and push to publish." : "Run `shadcn build` (or the registry:build script) to generate public/r/ JSON files."}
`;

  // GitHub source registries have no app shell, so write a static llms.txt
  // at the repo root rather than a framework route.
  if (isGithub) {
    writeFile(join(dir, "llms.txt"), content);
    return;
  }

  if (config.framework === "nextjs") {
    // Generate a Next.js route handler for /llms.txt
    writeFile(
      join(dir, "app/llms.txt/route.ts"),
      `export function GET() {
  const content = ${JSON.stringify(content)};

  return new Response(content, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "public, max-age=3600",
    },
  });
}
`
    );
  } else {
    // Static file for non-Next.js frameworks
    writeFile(join(dir, "public/llms.txt"), content);
  }
}
