import type { ProjectConfig } from "../types.js";
import { writeFile, ensureDir } from "../utils.js";
import { join } from "node:path";

/**
 * Generates a component preview system for docs pages.
 *
 * For Next.js + Fumadocs:
 *   - Creates a preview route at /preview/[name] that renders components in isolation
 *   - Creates a PreviewFrame component that embeds the preview in an iframe
 *   - Works with MDX docs pages
 *
 * For other frameworks:
 *   - Creates a standalone preview page pattern
 */
export function generatePreview(config: ProjectConfig): void {
  const dir = config.directory;
  const style = config.style;

  if (config.framework === "nextjs") {
    generateNextjsPreview(config);
  }

  // Always generate the component preview component (non-iframe version)
  // This is already generated by fumadocs.ts, so only generate for non-fumadocs
  if (config.docsEngine !== "fumadocs") {
    writeFile(
      join(dir, "components/component-preview.tsx"),
      `"use client"

import * as React from "react"
import { cn } from "@/lib/utils"

interface ComponentPreviewProps {
  children: React.ReactNode
  className?: string
}

export function ComponentPreview({ children, className }: ComponentPreviewProps) {
  return (
    <div
      className={cn(
        "not-prose flex min-h-[200px] w-full items-center justify-center rounded-xl border bg-card p-8",
        className
      )}
    >
      {children}
    </div>
  )
}
`
    );
  }
}

function generateNextjsPreview(config: ProjectConfig): void {
  const dir = config.directory;
  const style = config.style;

  // Preview route — renders a component in isolation for iframe embedding
  ensureDir(join(dir, "app/preview/[name]"));

  writeFile(
    join(dir, "app/preview/[name]/page.tsx"),
    `import { notFound } from "next/navigation"
import * as React from "react"

/**
 * Component preview page — renders a single component in isolation.
 *
 * Used by the PreviewFrame component to embed live previews in docs via iframe.
 * Add your components to the PREVIEWS map below.
 */

// Import your component demos here
// import { ButtonDemo } from "@/components/examples/button-demo"
// import { CardDemo } from "@/components/examples/card-demo"

const PREVIEWS: Record<string, React.ComponentType> = {
  // Add entries as you create components:
  // button: ButtonDemo,
  // card: CardDemo,
}

export default async function PreviewPage(props: {
  params: Promise<{ name: string }>
}) {
  const { name } = await props.params
  const Preview = PREVIEWS[name]

  if (!Preview) notFound()

  return (
    <div className="flex min-h-screen items-center justify-center p-8">
      <Preview />
    </div>
  )
}

export function generateStaticParams() {
  return Object.keys(PREVIEWS).map((name) => ({ name }))
}
`
  );

  // Preview layout — minimal, no nav/footer
  writeFile(
    join(dir, "app/preview/layout.tsx"),
    `import "../globals.css"

export default function PreviewLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="antialiased">{children}</body>
    </html>
  )
}
`
  );

  // PreviewFrame component for embedding in docs
  writeFile(
    join(dir, "components/preview-frame.tsx"),
    `"use client"

import * as React from "react"
import { cn } from "@/lib/utils"

interface PreviewFrameProps {
  /** Component name — matches the key in the PREVIEWS map. */
  name: string
  /** Height of the preview iframe. */
  height?: number | string
  className?: string
}

/**
 * Embeds a live component preview in an iframe.
 *
 * Usage in MDX:
 * \`\`\`mdx
 * import { PreviewFrame } from "@/components/preview-frame"
 *
 * <PreviewFrame name="button" />
 * \`\`\`
 */
export function PreviewFrame({ name, height = 300, className }: PreviewFrameProps) {
  return (
    <div
      className={cn(
        "not-prose w-full overflow-hidden rounded-xl border bg-background",
        className
      )}
    >
      <iframe
        src={\`/preview/\${name}\`}
        title={\`\${name} preview\`}
        className="w-full border-0"
        style={{ height: typeof height === "number" ? \`\${height}px\` : height }}
        loading="lazy"
      />
    </div>
  )
}
`
  );
}
